from datetime import datetime
from elasticsearch import Elasticsearch, helpers
import configparser
# password
# FGs2odBSOX*T2gS8sl55
# HTTP Fingerprint
# 4973741232cbcdb5af1c95c33a5c15f90baa0679ad8d57d581414b5ef2f53778
# enrollment token
# eyJ2ZXIiOiI4LjQuMiIsImFkciI6WyIxNzIuMTguMC4yOjkyMDAiXSwiZmdyIjoiNDk3Mzc0MTIzMmNiY2RiNWFmMWM5NWMzM2E1YzE1ZjkwYmFhMDY3OWFkOGQ1N2Q1ODE0MTRiNWVmMmY1Mzc3OCIsImtleSI6ImVhNDVYWU1CNlE1elk4U2N6b3pDOjBkRjJRdEJLUTU2MGJMX2Y4a09FSUEifQ==
# 
ELASTIC_PASSWORD = "FGs2odBSOX*T2gS8sl55"
CERT_FINGERPRINT = "4973741232cbcdb5af1c95c33a5c15f90baa0679ad8d57d581414b5ef2f53778"
es = Elasticsearch('https://localhost:9200',ca_certs="http_ca.crt", basic_auth=("elastic", ELASTIC_PASSWORD))
doc = {
    'author': 'author_name',
    'text': 'Interensting content...',
    'timestamp': datetime.now(),
}
resp = es.index(index="test-index", id=1, document=doc)
print(resp['result'])
es.info()

# Password for the 'elastic' user generated by Elasticsearch, note: this is all local lmao, so unless we actually deploy this, no biggie.
ELASTIC_PASSWORD = "lWwjJoVHt50J00-WaYzm"

# CERT_FINGERPRINT
CERT_FINGERPRINT = "B7:F7:50:A9:18:D7:E4:B9:AD:48:F9:82:93:74:09:39:23:45:67:C7:6C:5C:3C:6B:35:B9:DA:4C:C4:B1:7F:86"