---
name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci -f
      - name: Run Linter
        run: npm run lint

  tester:
    name: Test UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci -f
      - name: Run tests
        run: npm run tests
