---
name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_BASH: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CPP: false
          VALIDATE_JAVA: false
          VALIDATE_JAVASCRIPT_ES: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
